[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
arc_testnet = "${ARC_TESTNET_RPC_URL}"

[profile.default.etherscan]
arc_testnet = { key = "${ARC_ETHERSCAN_API_KEY}" }

